DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ROLE;

CREATE TABLE ROLE(
    ROLE_ID BIGINT AUTO_INCREMENT NOT NULL,
    ROLE_NAME VARCHAR(255) UNIQUE NOT NULL,
    PRIMARY KEY (ROLE_ID)
);

CREATE TABLE USER(
    USER_ID BIGINT AUTO_INCREMENT NOT NULL,
    LOGIN VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY(USER_ID),
    FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

INSERT INTO ROLE (ROLE_ID, ROLE_NAME) VALUES (1, 'USER');
INSERT INTO ROLE (ROLE_ID, ROLE_NAME) VALUES (2, 'ADMIN');

INSERT INTO USER(USER_ID,LOGIN,PASSWORD,EMAIL,FIRST_NAME,LAST_NAME, BIRTHDAY, ROLE_ID) VALUES (1,'user','user','user@gmail.com','Vlad','Shakhno','1993-07-28',1);
INSERT INTO USER(USER_ID,LOGIN,PASSWORD,EMAIL,FIRST_NAME,LAST_NAME, BIRTHDAY, ROLE_ID) VALUES (2,'admin','admin','admin@gmail.com','John','Konstantin','1980-01-01',2);

