version: "3"
services:
  db:
    container_name: shakhno-db
    image: buildo/h2database
    hostname: shakhno-h2
    ports:
      - "8082:8082"
    volumes:
      - ./DDL_Docker.sql:/docker-entrypoint-initdb.d/DDL_Docker.sql
    restart: always

  app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
  api:
    build: angular-app
    depends_on:
      - app
    ports:
      - 4200:4200