--DROP SCHEMA IF EXISTS JDBC_TASK;
--CREATE SCHEMA IF NOT EXISTS JDBC_TASK;

--DROP TABLE IF EXISTS JDBC_TASK.ROLES;
--DROP TABLE IF EXISTS JDBC_TASK.USERS;

CREATE TABLE IF NOT EXISTS ROLES(
    role_id IDENTITY,
    role_name VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS(
    user_id IDENTITY,
    login VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    birthday DATE,
    role_id bigint,
    FOREIGN KEY(role_id) REFERENCES ROLES(role_id) ON DELETE CASCADE
ON UPDATE CASCADE
);


