CREATE TABLE ROLE(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE USER(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    LOGIN VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID)
);