version: "3"
services:
  db:
    container_name: shakhno-db
    image: buildo/h2database
    hostname: shakhno-h2
    ports:
      - "8082:8082"
    volumes:
      - ./DDL_Docker.sql:/docker-entrypoint-initdb.d/DDL_Docker.sql
    restart: always
  backend:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
  front:
    build: angular-app
    depends_on:
      - backend
    ports:
      - 4200:4200
  api:
    build: api
    depends_on:
      - backend
    ports:
      - 9000:8085