DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ROLE;

CREATE TABLE ROLE(
    ROLE_ID BIGINT AUTO_INCREMENT NOT NULL,
    ROLE_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ROLE_ID)
);

CREATE TABLE USER(
    USER_ID BIGINT AUTO_INCREMENT NOT NULL,
    LOGIN VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    BIRTHDAY DATE,
    ROLE_ID BIGINT,
    PRIMARY KEY(USER_ID),
    FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

INSERT INTO ROLE (ROLE_ID, ROLE_NAME) VALUES (1, 'ADMIN');
INSERT INTO ROLE (role_id, role_name) VALUES (2, 'USER');

INSERT INTO USER(USER_ID,LOGIN,PASSWORD,EMAIL,FIRST_NAME,LAST_NAME, BIRTHDAY, ROLE_ID) VALUES (1,'ad','ad','ad@gmail.com','Serhii','Yevt','1993-07-28',1);
INSERT INTO USER(USER_ID,LOGIN,PASSWORD,EMAIL,FIRST_NAME,LAST_NAME, BIRTHDAY, ROLE_ID) VALUES (2,'user','user','customer@gmail.com','firstF','firstS','1980-01-01',2);

