--DROP SCHEMA IF EXISTS JDBC_TASK;
--CREATE SCHEMA IF NOT EXISTS JDBC_TASK;

--DROP TABLE IF EXISTS JDBC_TASK.ROLE;
--DROP TABLE IF EXISTS JDBC_TASK.USER;

CREATE TABLE IF NOT EXISTS ROLE(
    ROLE_ID BIGINT AUTO_INCREMENT NOT NULL,
    ROLE_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ROLE_ID)
);

CREATE TABLE IF NOT EXISTS USER (
    USER_ID BIGINT AUTO_INCREMENT NOT NULL,
    LOGIN VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    BIRTHDAY DATE,
    ROLE_ID BIGINT,
    PRIMARY KEY(USER_ID),
    FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

